// Replies for `h!you` — reactions to a direct provocation/compliment aimed at
// Tosch. Complete lines (some are image/gif links); used verbatim.
export const COMEBACKS = [
   'After hearing what you just said, I realized that honest people still do exist!',
   'Are you a spy? Who sent you?',
   'Are you hitting on me?',
   'Awww... now I want to throw a rainbow at you.',
   'Careful, you might get burned.',
   'Coming from you, that means a lot!',
   'Compliment accepted.',
   'Do you really think I care about your opinion, lol?',
   'Enough of that!',
   'Finally, I found someone who agrees with my parents.',
   "Flattery won't get you anywhere, fella. Scram!",
   "Give me a quill and I'll give you my autograph.",
   "I'd tell you how, but you would have to pay me.",
   "I'm being watched. Act normal.",
   "I'm glad I made your day brighter.",
   "I'm sorry, but you can't afford it.",
   "I'm warning you, I'm too hot for you to handle.",
   'I can see that honesty is still the best policy.',
   'I get that a lot!',
   'I know. Wish I could say the same about you.',
   'I love you too!',
   'I love your honesty and sincerity.',
   'I would return the compliment, but I swore to tell the truth and nothing but the truth.',
   "If I had a dollar for every compliment I've received so far, I'd be a billionaire.",
   "Is that the best you've got?",
   "It's extremely rare for me to hear that.",
   "It's my duty to spread beauty in the world.",
   'It must be the meds kicking in.',
   'Just today? What about yesterday?',
   "Look who's talking, lol.",
   'Much obliged!',
   'No takebacks, okay!',
   'Not since the accident.',
   'Not this again... take a number and wait in line.',
   "Oh, I wish you'd experience it as well.",
   'Oh, stop it, you.',
   'Oh, such discerning eyes!',
   'Peace be with you!',
   'Shucks, my fluffy neck!',
   'Sorry, you must have mistaken me for someone else.',
   'Stop it before I fall in love with you.',
   'Thanks, but I prefer to be noticed for my intellectual capacity.',
   'Thanks, fan!',
   'Thanks, I sacrificed many lives for it.',
   'Thanks, I woke up like this.',
   'Well, that makes two of us!',
   'What do you need?',
   'Who told you to tell me that?',
   "You'll get there, eventually.",
   "You're not the first one to tell me that today.",
   'You know what? I like you.',
   'You must be looking at a mirror.',
   'I am gonna kill you with all my floof.',
   'Soon, I will drink from your skull.',
] as const;
