// Curated insults for `h!hate`. Complete sentences — used verbatim.
export const INSULTS = [
   'I hate you.',
   'You suck.',
   'You = noob.',
   'You are probably the worst person in Dunia.',
   'Uninstall Discord please.',
   "I wouldn't even buy you if you were a slave.",
   "I don't know how is that even possible to suck as much as you.",
   'If laughter is the best medicine, your face must be curing the world.',
   "You're so ugly, you scared the crap out of the toilet.",
   "It's better to let someone think you are an idiot than to open your mouth and prove it.",
   "I'm jealous of people that don't know you!",
   "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
   "I don't know what makes you so stupid, but it really works.",
   "I'd slap you, but that would be animal abuse.",
   'They say opposites attract. I hope you meet someone who is good-looking, intelligent, and cultured.',
   "If ugly were a crime, you'd get a life sentence.",
   'Your mind is on vacation but your mouth is working overtime.',
   'Shock me, say something intelligent.',
   "I don't know what your problem is, but I'll bet it's hard to pronounce.",
   "You're like Monday mornings, nobody likes you.",
   'To make you laugh on Saturday, I need to tell you a joke on Wednesday.',
   "If you really spoke your mind, you'd be speechless.",
   "Every time I'm next to you, I get a fierce desire to be alone.",
   "Don't you have a terribly empty feeling - in your skull?",
   'Are you always this stupid or is today a special occasion?',
   "Mirrors don't lie, and lucky for you, they also don't laugh.",
   'No wonder everyone talks about you behind your back.',
   'Your face makes onions cry.',
   "If you were twice as smart, you'd still be stupid.",
   "I wasn't born with enough middle fingers to let you know how I feel about you.",
   "You look like something I'd draw with my left hand.",
   'Of course I talk like an idiot... How else would you understand me?',
   'What are you doing here? Did someone leave your cage open?',
   "I'd love to insult you, but I won't do as well as nature did.",
   "You're so ugly the only dates you get are on a calendar.",
   "You're the reason they invented double doors.",
   "You're so dumb, I bet your pet teaches you tricks.",
   "If you were on fire and I had water, I'd drink it.",
   "You didn't just fall out of the stupid tree, you were dragged through dumbass forest.",
   "Keep rolling your eyes, maybe you'll find a brain back there.",
   "There's only one problem with your face... I can see it.",
   "I bet your brain feels good as new, seeing that you've never used it.",
   'Do you still love nature, despite what it did to you?',
   "Those clothes don't make you look stupid. You make you look stupid.",
] as const;
